// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApqjh-Y0u3Bynz_J4OYTDvYn6HBRBlPA8',
    appId: '1:600649128608:web:8afe37267e9a2a492947c5',
    messagingSenderId: '600649128608',
    projectId: 'finallyfirebase-51d8b',
    authDomain: 'finallyfirebase-51d8b.firebaseapp.com',
    storageBucket: 'finallyfirebase-51d8b.appspot.com',
    measurementId: 'G-V904RZDXXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDznvcIhtIsUDifWDD3UmAxIcuWTyBEVys',
    appId: '1:600649128608:android:5c50e0a4758cac2a2947c5',
    messagingSenderId: '600649128608',
    projectId: 'finallyfirebase-51d8b',
    storageBucket: 'finallyfirebase-51d8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pc9ioAiED0OLT3wprzWaFgpwk5Qr4fg',
    appId: '1:600649128608:ios:158e53746690e6b82947c5',
    messagingSenderId: '600649128608',
    projectId: 'finallyfirebase-51d8b',
    storageBucket: 'finallyfirebase-51d8b.appspot.com',
    iosBundleId: 'com.affafistibsharazhar.finallyfirebase',
  );
}
